runtime: python39

automatic_scaling:
  max_instances: 2

handlers:
- url: /static/
  static_dir: static/
  secure: always
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  secure: always
- url: /
  static_files: static/html/index.html
  upload: static/html/index.html
  secure: always
